import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Header } from "next/dist/lib/load-custom-routes";

export default function Home() {
  return (
    <>
      <Head>
        <title>To Do </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <h1>To Do Assistant</h1>
            <button className="pure-button">Login</button>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <h5>This is the footer</h5>
      </footer>
    </>
  );
}
