import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useRouter } from "next/router";
import { useSignIn, useUser } from "@clerk/nextjs";

export default function Home() {
    const { isSignedIn, user, isLoaded } = useUser();

    // Redirect using Nextjs
    let router = useRouter();
    function Login() {
        router.push("./sign-in");
    }

    function LoggedIn() {
        router.push("./todos");
    }

    // // In case the user signs out while on the page.
    if (!isLoaded) {
        return <span> loading .......</span>;
    }

    //Redirect to user's page if logged in
    if (isSignedIn) {
        return (
            <>
                <div>
                    {/* The current sign in attempt status is {signIn.status}. */}
                    <div>Hello: {user.fullName}</div>
                    {(onload = LoggedIn())}
                </div>
            </>
        );
    }

    return (
        <>
            <Head>
                <title>To Do </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <h1>To Do Assistant </h1>

                    <br></br>
                    <div>
                        <button className='pure-button' onClick={Login}>
                            Login
                        </button>
                    </div>
                </div>
            </main>
            <footer className={styles.footer}>
                <h5>This is the footer</h5>
            </footer>
        </>
    );
}
